---
blank_issues_enabled: true
contact_links:
  - about: "e.g. git, kubectl, npm etc"
    name: My issue relates to a specific CLI tool
    url: "https://github.com/withfig/autocomplete/issues/new/choose"
  - about: "Find detailed guides about common support issues in our forum"
    name: "💬  GitHub Discussions"
    url: "https://github.com/withfig/fig/discussions"
  - about: "Get instant support from the Fig Community Discord"
    name: "👋  Discord"
    url: "https://fig.io/community"
  - about: "Get support from the Fig team at hello@fig.io"
    name: "📩  Email"
    url: "https://tinyurl.com/y4m9zqlw"
