name: Main Issue Template
description: All issues except ones relating to specific CLI tools
labels: [NEED_TO_LABEL]
body:
- type: checkboxes
  attributes:
    label: Sanity checks
    options:
    - label: "I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue"
      required: true
    - label: "I have run `fig doctor` in the affected terminal session"
      required: true
    - label: "I have run `fig restart` and tested again (tell us if that fixed it)"
      required: true
- type: textarea
  attributes:
    label: Issue Details
    description: What happens? What do you expect? How do we reproduce?
    # Because we are using hashtags at the start of a line, we must put the value in quotes. We cannot use YAML's multiline syntax with the pipe symbol
    value: |
      ### Description:
      <!--
      Explain what you expected to happen, what actually happened, and how we can reproduce it.
      We can fix it faster if you add a video or screenshot!
      <!-- ----- WRITE BELOW THIS LINE ----- -->
      
      
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: "Run `fig diagnostic` and paste the output below. If you can't, tell us any information you think is relevant (OS, m1 etc)"
    render: bash
  validations:
    required: true
