name: "Issue Template"
description: "File an issue related to Fig"
title: "bug: "
labels: ["NEED_TO_LABEL", "type:bug"]

body:
- type: checkboxes
  id: "checks"
  attributes:
    label: "Checks"
    options:
    - label: "I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue"
      required: true
    - label: "I have run `fig doctor` in the affected terminal session"
      required: true
    - label: "I have run `fig restart` and replicated the issue again"
      required: true

- type: input
  id: "os"
  attributes:
    label: "Operating System"
  validations: required: true

- type: textarea
  id: "details"
  attributes:
    label: "Issue Details"
    description: "Tell us what happened, and what the expected behaviour is. Please provide a screenshot or video if possible."
  validations:
    required: true

- type: textarea
  id: "environment"
  attributes:
    label: "Environment"
    description: "If possible, run `fig diagnostic` and paste the output below."
    render: yaml
